// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initDB_modifyToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initDB_modifyToken));
        
        string IMigrationMetadata.Id
        {
            get { return "202305012134048_initDB_modifyToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
