// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class seedingagaindoctor1member : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedingagaindoctor1member));
        
        string IMigrationMetadata.Id
        {
            get { return "202305100628378_seedingagaindoctor1member"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
